import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-cross-border-vat-refund-recovery",
  "engine": "recovery",
  "title": "Cross-Border VAT Refund Recovery",
  "shortTitle": "Cross-Border VAT Refund Recovery",
  "tagline": "Recover foreign VAT from eligible business expenses through country-specific evidence, deadlines, and refund submissions.",
  "industry": "Indirect Tax Recovery",
  "buyer": "Multinational companies and travel-heavy enterprises",
  "uiPort": 4686,
  "apiPort": 5686,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Cross-Border VAT Refund Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds in one accountable workflow. Recover foreign VAT from eligible business expenses through country-specific evidence, deadlines, and refund submissions.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Cross-Border VAT Refund Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("entity-vat-profile","CBV01","Entity VAT profile","Execute entity vat profile using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed entity vat profile decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Entity VAT profile Reference","text","CBV01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("supplier-invoice-ingestion","CBV02","Supplier invoice ingestion","Execute supplier invoice ingestion using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed supplier invoice ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Supplier invoice ingestion Reference","text","CBV02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("invoice-validity-checks","CBV03","Invoice validity checks","Execute invoice validity checks using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed invoice validity checks decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Invoice validity checks Reference","text","CBV03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("country-eligibility-rules","CBV04","Country eligibility rules","Execute country eligibility rules using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed country eligibility rules decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Country eligibility rules Reference","text","CBV04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("expense-category-classification","CBV05","Expense category classification","Execute expense category classification using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed expense category classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Expense category classification Reference","text","CBV05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("business-purpose-evidence","CBV06","Business purpose evidence","Execute business purpose evidence using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed business purpose evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Business purpose evidence Reference","text","CBV06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("partial-deductibility-calculation","CBV07","Partial deductibility calculation","Execute partial deductibility calculation using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed partial deductibility calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Partial deductibility calculation Reference","text","CBV07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("domestic-registration-exclusion","CBV08","Domestic registration exclusion","Execute domestic registration exclusion using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed domestic registration exclusion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Domestic registration exclusion Reference","text","CBV08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("original-document-control","CBV09","Original document control","Execute original document control using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed original document control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Original document control Reference","text","CBV09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("minimum-claim-threshold","CBV10","Minimum claim threshold","Execute minimum claim threshold using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed minimum claim threshold decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Minimum claim threshold Reference","text","CBV10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("filing-deadline-monitoring","CBV11","Filing deadline monitoring","Execute filing deadline monitoring using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed filing deadline monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Filing deadline monitoring Reference","text","CBV11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("portal-claim-preparation","CBV12","Portal claim preparation","Execute portal claim preparation using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed portal claim preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Portal claim preparation Reference","text","CBV12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("tax-authority-query-workflow","CBV13","Tax authority query workflow","Execute tax authority query workflow using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed tax authority query workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Tax authority query workflow Reference","text","CBV13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("refund-reconciliation","CBV14","Refund reconciliation","Execute refund reconciliation using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed refund reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Refund reconciliation Reference","text","CBV14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]}),
feature("country-category-analytics","CBV15","Country category analytics","Execute country category analytics using supplier invoices, VAT registrations, expense categories, business purpose, country rules, deductible percentages, original documents, portals, deadlines, claims, and refunds.","Produce a governed country category analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Entity / Country Refund Claim","text","Entity / Country Refund Claim · Standard Case"],["caseReference","Country category analytics Reference","text","CBV15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1098750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1329488],["domainDriver","Expense Category","select","Travel",["Travel","Professional services","Trade fair"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Entity VAT profile case","Supplier invoice ingestion case","Invoice validity checks case","Country eligibility rules case","Expense category classification case"]})
]);
